http:
  services:
    szakdoga2025-microservice1:
      weighted:
        services:
        - name: szakdoga2025-microservice1-blue
          weight: 50
        - name: szakdoga2025-microservice1-green
          weight: 50
    szakdoga2025-microservice1-blue:
      loadBalancer:
        servers:
        - url: http://szakdoga2025-microservice1-blue:8000
    szakdoga2025-microservice1-green:
      loadBalancer:
        servers:
        - url: http://szakdoga2025-microservice1-green:8000
    szakdoga2025-microservice2:
      weighted:
        services:
        - name: szakdoga2025-microservice2-blue
          weight: 61
        - name: szakdoga2025-microservice2-green
          weight: 39
    szakdoga2025-microservice2-blue:
      loadBalancer:
        servers:
        - url: http://szakdoga2025-microservice2-blue:8000
    szakdoga2025-microservice2-green:
      loadBalancer:
        servers:
        - url: http://szakdoga2025-microservice2-green:8000
    szakdoga2025-microservice3:
      weighted:
        services:
        - name: szakdoga2025-microservice3-blue
          weight: 0
        - name: szakdoga2025-microservice3-green
          weight: 100
    szakdoga2025-microservice3-blue:
      loadBalancer:
        servers:
        - url: http://szakdoga2025-microservice3-blue:8000
    szakdoga2025-microservice3-green:
      loadBalancer:
        servers:
        - url: http://szakdoga2025-microservice3-green:8000
    dashboard:
      loadBalancer:
        servers:
        - url: http://szakdoga2025-dashboard:3000
    deployment-engine:
      loadBalancer:
        servers:
        - url: http://szakdoga2025-deployment-engine:8000
  routers:
    m1:
      rule: Host(`microservice1.com`)
      service: szakdoga2025-microservice1
    m2:
      rule: Host(`microservice2.com`)
      service: szakdoga2025-microservice2
    m3:
      rule: Host(`microservice3.com`)
      service: szakdoga2025-microservice3
    dashboard:
      rule: PathPrefix(`/dashboard`)
      service: dashboard
      middlewares:
      - strip-prefix
    deployment-engine:
      rule: PathPrefix(`/api/deploy`)
      service: deployment-engine
      middlewares:
      - strip-prefix
  middlewares:
    strip-prefix:
      stripPrefix:
        prefixes:
        - /dashboard
        - /api/deploy
