# docker/traefik/traefik.yml
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

# API és Dashboard konfigurálása
api:
  insecure: true  # Fejlesztési környezetben, production-ben false legyen!
  dashboard: true

# Szolgáltatások automatikus felderítése
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: "traefik-network"
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

# Log beállítások
log:
  level: "INFO"

# Tanúsítvány kezelés (fejlesztési környezetben nem szükséges)
# certificatesResolvers:
#   letsencrypt:
#     acme:
#       email: your-email@example.com
#       storage: /etc/traefik/acme.json
#       httpChallenge:
#         entryPoint: web