
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"


# API és Dashboard konfigurálása
api:
  insecure: true  
  dashboard: true

# Szolgáltatások automatikus felderítése
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: "traefik-network"
  file:
    filename: "/etc/traefik/dynamic/services.yml"
    watch: true

# Log beállítások
log:
  level: "INFO"

